// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import '@hotwired/turbo-rails'
import 'controllers'
import 'popper'
import 'bootstrap'
import 'filepond'
import 'custom/post_images_filepond'
import 'filepond-plugin-image-preview'
import 'filepond-plugin-file-validate-type'
import 'filepond-plugin-file-validate-size'
import 'leaflet'
import 'leaflet-geocoder'
import 'custom/leaflet_map'
import 'sweetalert2'
import 'custom/delete_confirmation_dialog'